# _config.yml

title: "GitHub Pages Frontend Framework"
description: "Ein einfaches Frontend Framework für GitHub Pages mit Jekyll"
author: "Dein Name"
baseurl: "" # Verwende deinen Projektpfad, z.B. "/meine-seite"
url: "https://ehy-training.github.io/html-basics/" # Deine GitHub Pages URL

markdown: kramdown