# _config.yml

title: "HTML und CSS Grundlagen"
description: "Eine einfache Website mit den wichtigsten Grundlagen zum Einstieg in das Web Development"
author: "Enno Hyttrek"
baseurl: "/html-basics" # Verwende deinen Projektpfad, z.B. "/meine-seite"
url: "https://ehy-training.github.io/html-basics/" # Deine GitHub Pages URL

markdown: kramdown